name: vanilla_sac_bipedal_walker_256batch_curriculum_attempt2
project: bipedal_walker_final
program: experimenting/bipedal_walker_training.py
method: bayes
metric:
  goal: maximize
  name: train/mean_reward_eval_smoothed
parameters:
  number_of_curriculums:
    values: [2, 3, 4, 5, 6, 7, 8, 9, 10]
  anti_curriculum:
    values: [True, False]
  max_train_steps_per_curriculum:
    values: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 200, 300, 400, 500]
  alpha:
    min: 0.0001
    max: 0.001
  beta:
    min: 0.0001
    max: 0.001
  theta:
    min: 0.0001
    max: 0.001
  gamma:
    min: 0.98
    max: 0.9999
  tau:
    min: 0.001
    max: 0.01
  grad_clip_value:
    min: 0.01
    max: 25.0
  functions_updates:
    values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]