name: rl_hyperparam_search_lunar_lander
project: rl_research_mbzuai
program: experimenting/lunar_lander_training.py
method: bayes
metric:
  goal: maximize
  name: train/mean_reward_eval
parameters:
  learning_rate:
    min: 0.00005
    max: 0.005
  gamma:
    values: [0.9, 0.95, 0.99]
  batch_size:
    values: [32, 64, 128]
  tau:
    min: 0.0001
    max: 0.01
  epsilon_decay:
    min: 0.0025
    max: 0.01
  first_layer_neurons:
    values: [32, 64, 128, 256]
  second_layer_neurons:
    values: [32, 64, 128, 256]
  initial_random_experiences:
    values: [5000, 10000, 20000, 25000, 30000, 35000, 40000, 45000, 50000]
  memory_capacity:
    values: [50000, 75000, 100000]
  grad_clip_value:
    min: 10
    max: 1000