name: rl_hyperparam_search_lunar_lander
project: rl_research_mbzuai
program: experimenting/lunar_lander_training.py
method: bayes
metric:
  goal: maximize
  name: train/mean_reward_eval
parameters:
  number_of_curriculums:
    values: [2, 3, 4, 5, 6, 7, 8, 9, 10]
  anti_curriculum:
    values: [True, False]
  max_train_steps_per_curriculum_criterion1:
    values: [500, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000]