name: rl_hyperparam_search_bipedal_walker
project: bipedal_walker_final
program: experimenting/bipedal_walker_training.py
method: bayes
metric:
  goal: maximize
  name: train/mean_reward_eval_smoothed
parameters:
  alpha:
    min: 0.0001
    max: 0.001
  beta:
    min: 0.0001
    max: 0.001
  theta:
    min: 0.0001
    max: 0.001
  gamma:
    min: 0.98
    max: 0.9999
  tau:
    min: 0.001
    max: 0.01
  grad_clip_value:
    min: 0.1
    max: 15.0
  functions_updates:
    values: [1, 2, 3, 4, 5]
  std_max:
    min: 1
    max: 20