name: rl_hyperparam_search_lunar_lander
project: rl_research_mbzuai
program: experimenting/lunar_lander_training.py
method: bayes
metric:
  goal: maximize
  name: train/mean_reward_eval_smoothed
parameters:
  learning_rate:
    min: 0.0001
    max: 0.005
  gamma:
    values: [0.99, 0.995, 0.999, 0.9995, 0.9999]
  tau:
    min: 0.0001
    max: 0.01
  epsilon_decay:
    min: 0.0075
    max: 0.015
  first_layer_neurons:
    values: [32, 64, 128, 256]
  second_layer_neurons:
    values: [32, 64, 128, 256]
  initial_random_experiences:
    values: [32, 256, 1024, 2048, 4096, 8192]
  memory_capacity:
    values: [50000, 75000, 100000]
  grad_clip_value:
    min: 0.5
    max: 10