name: rl_hyperparam_search_lunar_lander
project: rl_research_mbzuai
program: experimenting/lunar_lander_training.py
method: bayes
metric:
  goal: maximize
  name: train/mean_reward_eval_smoothed
parameters:
  learning_rate:
    min: 0.00005
    max: 0.001
  gamma:
    min: 0.9
    max: 0.999
  epsilon_decay:
    min: 500
    max: 1000
  first_layer_neurons:
    values: [16, 32, 64, 128, 256, 512]
  second_layer_neurons:
    values: [16, 32, 64, 128, 256, 512]
  initial_random_experiences:
    values: [5000, 10000, 15000, 20000, 25000, 30000, 35000, 40000, 45000, 50000]
  memory_capacity:
    values: [50000, 75000, 100000]
  