wandb_version: 1

architecture:
  desc: null
  value: IMPALA_large_CNN
dataset:
  desc: null
  value: procgen:procgen-bossfight-v0
learning_rate:
  desc: null
  value: 0.001
episodes:
  desc: null
  value: 200
max_steps:
  desc: null
  value: 1000
batch_size:
  desc: null
  value: 32
gamma:
  desc: null
  value: 0.99
epsilon_start:
  desc: null
  value: 0.99
epsilon_decay:
  desc: null
  value: 250000
epsilon_min:
  desc: null
  value: 0.05
tau:
  desc: null
  value: 0.001
memory_len:
  desc: null
  value: 200000
optimizer:
  desc: null
  value: "Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n\
    \    capturable: False\n    differentiable: False\n    eps: 1e-08\n    foreach:\
    \ None\n    fused: None\n    lr: 0.001\n    maximize: False\n    weight_decay:\
    \ 0\n)"
criterion:
  desc: null
  value: MSELoss()
device:
  desc: null
  value: cuda
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696617958.187838
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 7
      - 16
      - 23
      4: 3.8.18
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: train/step
      6:
      - 3
